//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioShopFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Ships = new HashSet<Ship>();
        }
    
        public System.Guid NidOrder { get; set; }
        public System.Guid NidUser { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public int state { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Zipcode { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<long> RefId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship> Ships { get; set; }
    }
}
