//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioShopFrontend.ZarinpalTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zarinpal.com/", ConfigurationName="ZarinpalTest.PaymentGatewayImplementationServicePortType")]
    public interface PaymentGatewayImplementationServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentRequest", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.PaymentRequestResponse PaymentRequest(AudioShopFrontend.ZarinpalTest.PaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestResponse> PaymentRequestAsync(AudioShopFrontend.ZarinpalTest.PaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentRequestWithExtra", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse PaymentRequestWithExtra(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentRequestWithExtra", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse> PaymentRequestWithExtraAsync(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentVerification", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse PaymentVerification(AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse> PaymentVerificationAsync(AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentVerificationWithExtra", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse PaymentVerificationWithExtra(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#PaymentVerificationWithExtra", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse> PaymentVerificationWithExtraAsync(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#GetUnverifiedTransactions", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse GetUnverifiedTransactions(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#GetUnverifiedTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse> GetUnverifiedTransactionsAsync(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest request);
        
        // CODEGEN: Generating message contract since element name MerchantID from namespace http://zarinpal.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="#RefreshAuthority", ReplyAction="*")]
        AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse RefreshAuthority(AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="#RefreshAuthority", ReplyAction="*")]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse> RefreshAuthorityAsync(AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequest", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentRequestRequestBody Body;
        
        public PaymentRequestRequest() {
        }
        
        public PaymentRequestRequest(AudioShopFrontend.ZarinpalTest.PaymentRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CallbackURL;
        
        public PaymentRequestRequestBody() {
        }
        
        public PaymentRequestRequestBody(string MerchantID, int Amount, string Description, string Email, string Mobile, string CallbackURL) {
            this.MerchantID = MerchantID;
            this.Amount = Amount;
            this.Description = Description;
            this.Email = Email;
            this.Mobile = Mobile;
            this.CallbackURL = CallbackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentRequestResponseBody Body;
        
        public PaymentRequestResponse() {
        }
        
        public PaymentRequestResponse(AudioShopFrontend.ZarinpalTest.PaymentRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authority;
        
        public PaymentRequestResponseBody() {
        }
        
        public PaymentRequestResponseBody(int Status, string Authority) {
            this.Status = Status;
            this.Authority = Authority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestWithExtraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestWithExtra", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequestBody Body;
        
        public PaymentRequestWithExtraRequest() {
        }
        
        public PaymentRequestWithExtraRequest(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentRequestWithExtraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AdditionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CallbackURL;
        
        public PaymentRequestWithExtraRequestBody() {
        }
        
        public PaymentRequestWithExtraRequestBody(string MerchantID, int Amount, string Description, string AdditionalData, string Email, string Mobile, string CallbackURL) {
            this.MerchantID = MerchantID;
            this.Amount = Amount;
            this.Description = Description;
            this.AdditionalData = AdditionalData;
            this.Email = Email;
            this.Mobile = Mobile;
            this.CallbackURL = CallbackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestWithExtraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestWithExtraResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponseBody Body;
        
        public PaymentRequestWithExtraResponse() {
        }
        
        public PaymentRequestWithExtraResponse(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentRequestWithExtraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authority;
        
        public PaymentRequestWithExtraResponseBody() {
        }
        
        public PaymentRequestWithExtraResponseBody(int Status, string Authority) {
            this.Status = Status;
            this.Authority = Authority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentVerification", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentVerificationRequestBody Body;
        
        public PaymentVerificationRequest() {
        }
        
        public PaymentVerificationRequest(AudioShopFrontend.ZarinpalTest.PaymentVerificationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentVerificationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Amount;
        
        public PaymentVerificationRequestBody() {
        }
        
        public PaymentVerificationRequestBody(string MerchantID, string Authority, int Amount) {
            this.MerchantID = MerchantID;
            this.Authority = Authority;
            this.Amount = Amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentVerificationResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentVerificationResponseBody Body;
        
        public PaymentVerificationResponse() {
        }
        
        public PaymentVerificationResponse(AudioShopFrontend.ZarinpalTest.PaymentVerificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentVerificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long RefID;
        
        public PaymentVerificationResponseBody() {
        }
        
        public PaymentVerificationResponseBody(int Status, long RefID) {
            this.Status = Status;
            this.RefID = RefID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerificationWithExtraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentVerificationWithExtra", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequestBody Body;
        
        public PaymentVerificationWithExtraRequest() {
        }
        
        public PaymentVerificationWithExtraRequest(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentVerificationWithExtraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Amount;
        
        public PaymentVerificationWithExtraRequestBody() {
        }
        
        public PaymentVerificationWithExtraRequestBody(string MerchantID, string Authority, int Amount) {
            this.MerchantID = MerchantID;
            this.Authority = Authority;
            this.Amount = Amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentVerificationWithExtraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentVerificationWithExtraResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponseBody Body;
        
        public PaymentVerificationWithExtraResponse() {
        }
        
        public PaymentVerificationWithExtraResponse(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class PaymentVerificationWithExtraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long RefID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExtraDetail;
        
        public PaymentVerificationWithExtraResponseBody() {
        }
        
        public PaymentVerificationWithExtraResponseBody(int Status, long RefID, string ExtraDetail) {
            this.Status = Status;
            this.RefID = RefID;
            this.ExtraDetail = ExtraDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnverifiedTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnverifiedTransactions", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequestBody Body;
        
        public GetUnverifiedTransactionsRequest() {
        }
        
        public GetUnverifiedTransactionsRequest(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class GetUnverifiedTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        public GetUnverifiedTransactionsRequestBody() {
        }
        
        public GetUnverifiedTransactionsRequestBody(string MerchantID) {
            this.MerchantID = MerchantID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnverifiedTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnverifiedTransactionsResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponseBody Body;
        
        public GetUnverifiedTransactionsResponse() {
        }
        
        public GetUnverifiedTransactionsResponse(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class GetUnverifiedTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authorities;
        
        public GetUnverifiedTransactionsResponseBody() {
        }
        
        public GetUnverifiedTransactionsResponseBody(int Status, string Authorities) {
            this.Status = Status;
            this.Authorities = Authorities;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshAuthorityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshAuthority", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequestBody Body;
        
        public RefreshAuthorityRequest() {
        }
        
        public RefreshAuthorityRequest(AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class RefreshAuthorityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ExpireIn;
        
        public RefreshAuthorityRequestBody() {
        }
        
        public RefreshAuthorityRequestBody(string MerchantID, string Authority, int ExpireIn) {
            this.MerchantID = MerchantID;
            this.Authority = Authority;
            this.ExpireIn = ExpireIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshAuthorityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshAuthorityResponse", Namespace="http://zarinpal.com/", Order=0)]
        public AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponseBody Body;
        
        public RefreshAuthorityResponse() {
        }
        
        public RefreshAuthorityResponse(AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://zarinpal.com/")]
    public partial class RefreshAuthorityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Status;
        
        public RefreshAuthorityResponseBody() {
        }
        
        public RefreshAuthorityResponseBody(int Status) {
            this.Status = Status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentGatewayImplementationServicePortTypeChannel : AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewayImplementationServicePortTypeClient : System.ServiceModel.ClientBase<AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType>, AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType {
        
        public PaymentGatewayImplementationServicePortTypeClient() {
        }
        
        public PaymentGatewayImplementationServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewayImplementationServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayImplementationServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayImplementationServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.PaymentRequestResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentRequest(AudioShopFrontend.ZarinpalTest.PaymentRequestRequest request) {
            return base.Channel.PaymentRequest(request);
        }
        
        public int PaymentRequest(string MerchantID, int Amount, string Description, string Email, string Mobile, string CallbackURL, out string Authority) {
            AudioShopFrontend.ZarinpalTest.PaymentRequestRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentRequestRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentRequestRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Amount = Amount;
            inValue.Body.Description = Description;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.CallbackURL = CallbackURL;
            AudioShopFrontend.ZarinpalTest.PaymentRequestResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentRequest(inValue);
            Authority = retVal.Body.Authority;
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentRequestAsync(AudioShopFrontend.ZarinpalTest.PaymentRequestRequest request) {
            return base.Channel.PaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestResponse> PaymentRequestAsync(string MerchantID, int Amount, string Description, string Email, string Mobile, string CallbackURL) {
            AudioShopFrontend.ZarinpalTest.PaymentRequestRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentRequestRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentRequestRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Amount = Amount;
            inValue.Body.Description = Description;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.CallbackURL = CallbackURL;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentRequestWithExtra(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest request) {
            return base.Channel.PaymentRequestWithExtra(request);
        }
        
        public int PaymentRequestWithExtra(string MerchantID, int Amount, string Description, string AdditionalData, string Email, string Mobile, string CallbackURL, out string Authority) {
            AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Amount = Amount;
            inValue.Body.Description = Description;
            inValue.Body.AdditionalData = AdditionalData;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.CallbackURL = CallbackURL;
            AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentRequestWithExtra(inValue);
            Authority = retVal.Body.Authority;
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentRequestWithExtraAsync(AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest request) {
            return base.Channel.PaymentRequestWithExtraAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraResponse> PaymentRequestWithExtraAsync(string MerchantID, int Amount, string Description, string AdditionalData, string Email, string Mobile, string CallbackURL) {
            AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentRequestWithExtraRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Amount = Amount;
            inValue.Body.Description = Description;
            inValue.Body.AdditionalData = AdditionalData;
            inValue.Body.Email = Email;
            inValue.Body.Mobile = Mobile;
            inValue.Body.CallbackURL = CallbackURL;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentRequestWithExtraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentVerification(AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest request) {
            return base.Channel.PaymentVerification(request);
        }
        
        public int PaymentVerification(string MerchantID, string Authority, int Amount, out long RefID) {
            AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentVerificationRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.Amount = Amount;
            AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentVerification(inValue);
            RefID = retVal.Body.RefID;
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentVerificationAsync(AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest request) {
            return base.Channel.PaymentVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationResponse> PaymentVerificationAsync(string MerchantID, string Authority, int Amount) {
            AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentVerificationRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentVerificationRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.Amount = Amount;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentVerificationWithExtra(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest request) {
            return base.Channel.PaymentVerificationWithExtra(request);
        }
        
        public int PaymentVerificationWithExtra(string MerchantID, string Authority, int Amount, out long RefID, out string ExtraDetail) {
            AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.Amount = Amount;
            AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentVerificationWithExtra(inValue);
            RefID = retVal.Body.RefID;
            ExtraDetail = retVal.Body.ExtraDetail;
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.PaymentVerificationWithExtraAsync(AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest request) {
            return base.Channel.PaymentVerificationWithExtraAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraResponse> PaymentVerificationWithExtraAsync(string MerchantID, string Authority, int Amount) {
            AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest inValue = new AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.PaymentVerificationWithExtraRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.Amount = Amount;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).PaymentVerificationWithExtraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.GetUnverifiedTransactions(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest request) {
            return base.Channel.GetUnverifiedTransactions(request);
        }
        
        public int GetUnverifiedTransactions(string MerchantID, out string Authorities) {
            AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest inValue = new AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequestBody();
            inValue.Body.MerchantID = MerchantID;
            AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).GetUnverifiedTransactions(inValue);
            Authorities = retVal.Body.Authorities;
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.GetUnverifiedTransactionsAsync(AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest request) {
            return base.Channel.GetUnverifiedTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsResponse> GetUnverifiedTransactionsAsync(string MerchantID) {
            AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest inValue = new AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.GetUnverifiedTransactionsRequestBody();
            inValue.Body.MerchantID = MerchantID;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).GetUnverifiedTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.RefreshAuthority(AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest request) {
            return base.Channel.RefreshAuthority(request);
        }
        
        public int RefreshAuthority(string MerchantID, string Authority, int ExpireIn) {
            AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest inValue = new AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.ExpireIn = ExpireIn;
            AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse retVal = ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).RefreshAuthority(inValue);
            return retVal.Body.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse> AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType.RefreshAuthorityAsync(AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest request) {
            return base.Channel.RefreshAuthorityAsync(request);
        }
        
        public System.Threading.Tasks.Task<AudioShopFrontend.ZarinpalTest.RefreshAuthorityResponse> RefreshAuthorityAsync(string MerchantID, string Authority, int ExpireIn) {
            AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest inValue = new AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequest();
            inValue.Body = new AudioShopFrontend.ZarinpalTest.RefreshAuthorityRequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.Authority = Authority;
            inValue.Body.ExpireIn = ExpireIn;
            return ((AudioShopFrontend.ZarinpalTest.PaymentGatewayImplementationServicePortType)(this)).RefreshAuthorityAsync(inValue);
        }
    }
}
